# this is used with the cost feature
currency:
  # accepts a spigot material or a placeholder - ex: '%vault_eco_balance%'
  unit: 'DIAMOND'
  # if using a placeholder, add the remove command here - ex: 'eco take {player} {amount}'
  remove-currency-commands:
    - 'msg {player} {amount} diamonds have been taken'
  # what you want before/after the currency ex: $ or €
  prefix: ''
  suffix: '&b♦'
  # how many decimals will be shown
  decimals: 0
# HeadDataBase or Base64
head:
  # set this to true if you want to be able to use heads as ranks in the gui
  enabled: true
  # What head will the ranks change to when they are completed - HeadDataBase index or Base64
  completed: 6269
# what you want to add to the requirement line when it is completed
requirement-completion:
  # beginning of line
  before: '&a&m'
  # before {req<x>}
  prefix: ''
  # after {req<x>}
  suffix: ''
  # at the end of the line
  after: ' &7(&a✓&7)'
# formatting of large numbers
number-formatting:
  # 0 - disabled
  # 1 - thousands
  # 2 - divisions
  type: 1
  # character every 3 digits ex: ',' = 10,000 | '.' = 10.000 | '' = 10000
  thousands: ','
  # makes the number smaller and adds a suffix ex: 1000 = 1K | 1234 = 1.23K | 5467900 = 5.47M
  divisions:
    # how many decimals to include after a division
    decimals: 1
    # the division and suffix
    1000: K
    1000000: M
    1000000000: B
    1000000000000: T
# rank name before player name
prefix:
  enabled: true
  # this will overwrite any other plugin that tries to edit the chat message before it
  # disable to work with other chat formatting, and remove {name} from format
  overwrite-previous: true
  # message format
  # {prefix} for the rank name
  # {name} for player name - must be used once and only once if overwrite is enabled
  # placeholders will be parsed
  format: '&7[{prefix}&7] &f{name} &*: &r'
  # name of beginning rank
  no-rank: '&fUnranked'
# gui options - the gui name is in language.yml
gui:
  # this will surround the ranks with fill items and expand the inventory size as new ranks are added
  auto-size: true
  fill-item: GRAY_STAINED_GLASS_PANE
  # this will replace the next arrow and pack arrows with the fill item unless more pages are available
  replace-page-items: true
  # what item will pop up when you are denied in the config
  # set to DISABLE to disable
  # set to RANK to only change it item name
  deny-click-item: STRUCTURE_VOID
  # if auto-size is enabled, then the next gui-options won't do anything
  # size of gui
  size: 27
  1:
    # which slots will be filled - <x> or <x>-<y> where x < y
    slot: 0-26
    # what item
    # items can either be preset items, or you can create a new item
    # in this case it is a preset item
    # preset items you can use include:
    # * fill - material set above as fill-item with no name
    # * next - next arrow
    # * back - back arrow
    # * exit - barrier named Exit that will close the GUI if clicked
    # * rank <x> - will fill in the rank number | if no number is specified, it will autofill the next rank
    item: fill
  2:
    slot: 0
    # actions that can be run when the item is clicked
    # [gui] <x> - goes to the <x> page of ranks
    # [exit] - closes the gui
    # [next] - opens the next page of ranks if available
    # [back] - opens the previous page of ranks if available
    # [command] - runs a command, {player} can be used
    actions:
      - '[gui] 1'
    # in this case, a new item is being created
    item:
      material: SUNFLOWER
      amount: 1
      enchanted: true
      hide-nbt: true
      name: '&e&lRank Menu'
      lore:
        - ''
        - '&6Complete requirements to'
        - '&6unlock special rewards'
        - ''
  3:
    slot: 18
    item: back
  4:
    slot: 26
    item: next
  5:
    slot: 22
    item: exit
  6:
    slot: 10-16
    item: rank

1:
  name: '&9&lStarter'
  # If HeadDataBase is installed, this will try and get a head ID, otherwise Base64
  head: 193
  # this item will be used if heads is disabled
  item: EMERALD_BLOCK
  # {cost} to get x/total - with prefix & suffix around each number
  # {req1} to get the first requirement x/total ({req2} {req3} etc)
  # lore will change from red to green after completion if there is ^^ included
  lore:
    - '&e<△> &c&lREQUIREMENTS &e<△>'
    - '&7￫ &fPrice: {cost}'
    - '&7￫ &fHours Played: {req3}'
    - '&7￫ &fMob Kills: {req1}'
    - '&7￫ &fStone Broken: {req2}'
    - '&e<△> &c&lREWARDS &e<△>'
    - '&7￫ &fabsolutely nothing'
  # this will change the lore when the rank is completed
  # this could be useful if you want to unlock lore or add a secret message
  completion-lore:
    enabled: false
    lore:
      - '&7*--------------*'
      - '&a&l&nRank Completed'
      - '&7*--------------*'
  hide-nbt: true
  requirements:
    #                        vv operator - can be "<=" ">=" "!=" "=" ">" "<" ||| true/false & text can only use "!=" & "="
    # papi placeholder vv    vv  vv required amount - Make sure you download the placeholder before you use it
    - '%statistic_mob_kills% >= 100'
    #- '%mcmmo_power_level% >= 5'
    - '%statistic_mine_block:STONE% >= 500'
    # playtime
    - '%statistic_hours_played% >= 1'
  # auto checks and takes away with options defined in currency
  cost: 3
  commands:
    # use {player} to replace it with the players name
    # does not need a '/' in front of the command
    - 'broadcast &e&lCongrats to &a{player} &e&lfor ranking up to &9&lStarter'
    #- 'lp user {player} promote playerranks'


