# this is used with the cost feature
currency:
  # accepts a spigot material or a placeholder - ex: '%vault_eco_balance%'
  unit: 'DIAMOND'
  # if using a placeholder, add the remove command here - ex: 'eco take {player} {amount}'
  remove-currency-commands:
    - 'msg {player} {amount} diamonds have been taken'
  # what you want before/after the currency ex: $ or €
  prefix: ''
  suffix: '&b♦'
  # how many decimals will be shown
  decimals: 0
# HeadDataBase or Base64
head:
  # set this to true if you want to be able to use heads as ranks in the gui
  enabled: true
  # What head will the ranks change to when they are completed - HeadDataBase index or Base64
  completed: 6269
# what you want to add to the requirement line when it is completed
requirement-completion:
  # beginning of line
  before: '&a&m'
  # before {req<x>}
  prefix: ''
  # after {req<x>}
  suffix: ''
  # at the end of the line
  after: ' &7(&a✓&7)'
# formatting of large numbers
number-formatting:
  # 0 - disabled
  # 1 - thousands
  # 2 - divisions
  type: 1
  # character every 3 digits ex: ',' = 10,000 | '.' = 10.000 | '' = 10000
  thousands: ','
  # makes the number smaller and adds a suffix ex: 1000 = 1K | 1234 = 1.23K | 5467900 = 5.47M
  divisions:
    # how many decimals to include after a division
    decimals: 1
    # the division and suffix
    1000: K
    1000000: M
    1000000000: B
    1000000000000: T
# rank name before player name
prefix:
  enabled: true
  # this will overwrite any other plugin that tries to edit the chat message before it
  # disable to work with other chat formatting, and remove {name} from format
  overwrite-previous: true
  # message format
  # {prefix} for the rank name
  # {name} for player name - must be used once and only once if overwrite is enabled
  # placeholders will be parsed
  format: '&7[{prefix}&7] &f{name} &*: &r'
  # name of beginning rank
  no-rank: '&fUnranked'




