name: NotRanks
version: ${project.version}
main: me.jadenp.notranks.NotRanks
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDataBase
  - Vault
authors: [ Not_Jaden ]
description: Simpler way to organize ranks
commands:
  notranks:
    usage: /notranks
    description: Opens up the rank GUI.
  notrankup:
    usage: /notrankup
    description: Ranks you up to the next level.
  notrankinfo:
    usage: /notrankinfo
    description: Shows a chat message on your current rank.
permissions:
  notranks.default:
    default: true
    description: use all of the default commands
  notranks.admin:
    default: op
    description: admin commands
